# Generated by Django 5.2.17 on 2026-08-17 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_backfill_user_households'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('suggested', 'suggested'), ('cooked', 'cooked'), ('rejected', 'rejected')], default='suggested', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('servings', models.PositiveSmallIntegerField()),
                ('time_minutes', models.PositiveSmallIntegerField()),
                ('steps', models.JSONField(default=list)),
                ('substitutions', models.JSONField(default=list)),
                ('safety_note', models.CharField(blank=True, default='', max_length=500)),
                ('rationale', models.TextField(blank=True, default='')),
                ('provider_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_suggestions', to='inventory.household')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('count', 'count'), ('each', 'each'), ('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters')], max_length=10)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('owned_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('missing_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rescued', models.BooleanField(default=False)),
                ('allocations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='inventory.household')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.mealsuggestion')),
            ],
            options={
                'ordering': ('suggestion', 'name'),
                'constraints': [models.UniqueConstraint(fields=('suggestion', 'name', 'unit'), name='unique_ingredient_per_suggestion')],
            },
        ),
    ]
