# Generated by Django 5.2.17 on 2026-08-17 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_mealsuggestion_mealingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_events', to='inventory.household')),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_event', to='inventory.mealsuggestion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
